{% set name = "dj-rest-auth" %}
{% set version = "5.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dj-rest-auth-{{ version }}.tar.gz
  sha256: aad7d912476169e9991547bf98645344d3939be2d7052098048d819524c115d9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - django >=3.2
    - djangorestframework >=3.13.0
    - python >=3.6
  run_constrained:
    - django-allauth >=0.40.0,<0.51.0

test:
  imports:
    - dj_rest_auth
    - dj_rest_auth.registration
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/iMerica/dj-rest-auth
  summary: Authentication and Registration in Django Rest Framework
  license: MIT
  license_file: LICENSE
  doc_url: https://dj-rest-auth.readthedocs.io/en/latest/index.html

extra:
  recipe-maintainers:
    - BastianZim
