{% set name = "dj-rest-auth" %}
{% set version = "5.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dj-rest-auth-{{ version }}.tar.gz
  sha256: 2337a17fc9ce35eb294c7dbd9a4c12c7e7e6d448eb827fc67415589204c39d35

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - django >=3.2,<5.0
    - djangorestframework >=3.13.0
    - python >=3.6
  run_constrained:
    - django-allauth >=0.40.0,<0.51.0

test:
  imports:
    - dj_rest_auth
    - dj_rest_auth.registration
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/iMerica/dj-rest-auth
  summary: Authentication and Registration in Django Rest Framework
  license: MIT
  license_file: LICENSE
  doc_url: https://dj-rest-auth.readthedocs.io/en/latest/index.html

extra:
  recipe-maintainers:
    - BastianZim
