{% set name = "dj-rest-auth" %}
{% set version = "7.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dj-rest-auth-{{ version }}.tar.gz
  sha256: 08dbc03a35223872da9f59bc2d7a71bec2e721aa69f7cdc84c7a329aeae1f86e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - django >=3.2,<6.0
    - djangorestframework >=3.13.0
    - python >=3.8

test:
  imports:
    - dj_rest_auth
    - dj_rest_auth.registration
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/iMerica/dj-rest-auth
  summary: Authentication and Registration in Django Rest Framework
  license: MIT
  license_file: LICENSE
  doc_url: https://dj-rest-auth.readthedocs.io/en/latest/index.html

extra:
  recipe-maintainers:
    - BastianZim
